/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: format.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "format.pb-c.h"
void   history_slow_plan_stat__init
                     (HistorySlowPlanStat         *message)
{
  static const HistorySlowPlanStat init_value = HISTORY_SLOW_PLAN_STAT__INIT;
  *message = init_value;
}
size_t history_slow_plan_stat__get_packed_size
                     (const HistorySlowPlanStat *message)
{
  assert(message->base.descriptor == &history_slow_plan_stat__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t history_slow_plan_stat__pack
                     (const HistorySlowPlanStat *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &history_slow_plan_stat__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t history_slow_plan_stat__pack_to_buffer
                     (const HistorySlowPlanStat *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &history_slow_plan_stat__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HistorySlowPlanStat *
       history_slow_plan_stat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HistorySlowPlanStat *)
     protobuf_c_message_unpack (&history_slow_plan_stat__descriptor,
                                allocator, len, data);
}
void   history_slow_plan_stat__free_unpacked
                     (HistorySlowPlanStat *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &history_slow_plan_stat__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor history_slow_plan_stat__field_descriptors[31] =
{
  {
    "estimate_start_up_cost_",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, estimate_start_up_cost_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "estimate_total_cost_",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, estimate_total_cost_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "estimate_plan_rows_",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, estimate_plan_rows_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "estimate_plan_width_",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, estimate_plan_width_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actual_nloops_",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, actual_nloops_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actual_start_up_",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, actual_start_up_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actual_total_",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, actual_total_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actual_rows_",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, actual_rows_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "childs",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(HistorySlowPlanStat, n_childs),
    offsetof(HistorySlowPlanStat, childs),
    &history_slow_plan_stat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node_type_",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, node_type_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "strategy_",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, strategy_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "partial_mode_",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, partial_mode_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sub_plan_name_",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, sub_plan_name_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operation_",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, operation_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object_name_",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, object_name_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "schema_",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, schema_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object_tag_",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, object_tag_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alia_name_",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, alia_name_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scan_dir_",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, scan_dir_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "idx_name_",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, idx_name_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "join_type_",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, join_type_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inner_unique_",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, inner_unique_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command_",
    23,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, command_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output_",
    24,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(HistorySlowPlanStat, n_output_),
    offsetof(HistorySlowPlanStat, output_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "relationship_",
    25,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, relationship_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_cost_",
    26,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, total_cost_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sample_method_",
    27,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, sample_method_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sampling_parameters_",
    28,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, sampling_parameters_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "repeatable_seed_",
    29,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, repeatable_seed_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sub_cost_",
    30,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, sub_cost_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "json_plan_",
    31,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, json_plan_),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned history_slow_plan_stat__field_indices_by_name[] = {
  4,   /* field[4] = actual_nloops_ */
  7,   /* field[7] = actual_rows_ */
  5,   /* field[5] = actual_start_up_ */
  6,   /* field[6] = actual_total_ */
  17,   /* field[17] = alia_name_ */
  8,   /* field[8] = childs */
  22,   /* field[22] = command_ */
  2,   /* field[2] = estimate_plan_rows_ */
  3,   /* field[3] = estimate_plan_width_ */
  0,   /* field[0] = estimate_start_up_cost_ */
  1,   /* field[1] = estimate_total_cost_ */
  19,   /* field[19] = idx_name_ */
  21,   /* field[21] = inner_unique_ */
  20,   /* field[20] = join_type_ */
  30,   /* field[30] = json_plan_ */
  9,   /* field[9] = node_type_ */
  14,   /* field[14] = object_name_ */
  16,   /* field[16] = object_tag_ */
  13,   /* field[13] = operation_ */
  23,   /* field[23] = output_ */
  11,   /* field[11] = partial_mode_ */
  24,   /* field[24] = relationship_ */
  28,   /* field[28] = repeatable_seed_ */
  26,   /* field[26] = sample_method_ */
  27,   /* field[27] = sampling_parameters_ */
  18,   /* field[18] = scan_dir_ */
  15,   /* field[15] = schema_ */
  10,   /* field[10] = strategy_ */
  29,   /* field[29] = sub_cost_ */
  12,   /* field[12] = sub_plan_name_ */
  25,   /* field[25] = total_cost_ */
};
static const ProtobufCIntRange history_slow_plan_stat__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 31 }
};
const ProtobufCMessageDescriptor history_slow_plan_stat__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HistorySlowPlanStat",
  "HistorySlowPlanStat",
  "HistorySlowPlanStat",
  "",
  sizeof(HistorySlowPlanStat),
  31,
  history_slow_plan_stat__field_descriptors,
  history_slow_plan_stat__field_indices_by_name,
  1,  history_slow_plan_stat__number_ranges,
  (ProtobufCMessageInit) history_slow_plan_stat__init,
  NULL,NULL,NULL    /* reserved[123] */
};
