/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: src/include/collect/format.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "src/include/collect/format.pb-c.h"
void   history_slow_plan_stat__init
                     (HistorySlowPlanStat         *message)
{
  static const HistorySlowPlanStat init_value = HISTORY_SLOW_PLAN_STAT__INIT;
  *message = init_value;
}
size_t history_slow_plan_stat__get_packed_size
                     (const HistorySlowPlanStat *message)
{
  assert(message->base.descriptor == &history_slow_plan_stat__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t history_slow_plan_stat__pack
                     (const HistorySlowPlanStat *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &history_slow_plan_stat__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t history_slow_plan_stat__pack_to_buffer
                     (const HistorySlowPlanStat *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &history_slow_plan_stat__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
HistorySlowPlanStat *
       history_slow_plan_stat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (HistorySlowPlanStat *)
     protobuf_c_message_unpack (&history_slow_plan_stat__descriptor,
                                allocator, len, data);
}
void   history_slow_plan_stat__free_unpacked
                     (HistorySlowPlanStat *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &history_slow_plan_stat__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   group_sort_key__init
                     (GroupSortKey         *message)
{
  static const GroupSortKey init_value = GROUP_SORT_KEY__INIT;
  *message = init_value;
}
size_t group_sort_key__get_packed_size
                     (const GroupSortKey *message)
{
  assert(message->base.descriptor == &group_sort_key__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t group_sort_key__pack
                     (const GroupSortKey *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &group_sort_key__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t group_sort_key__pack_to_buffer
                     (const GroupSortKey *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &group_sort_key__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GroupSortKey *
       group_sort_key__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GroupSortKey *)
     protobuf_c_message_unpack (&group_sort_key__descriptor,
                                allocator, len, data);
}
void   group_sort_key__free_unpacked
                     (GroupSortKey *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &group_sort_key__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   group_keys__init
                     (GroupKeys         *message)
{
  static const GroupKeys init_value = GROUP_KEYS__INIT;
  *message = init_value;
}
size_t group_keys__get_packed_size
                     (const GroupKeys *message)
{
  assert(message->base.descriptor == &group_keys__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t group_keys__pack
                     (const GroupKeys *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &group_keys__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t group_keys__pack_to_buffer
                     (const GroupKeys *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &group_keys__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GroupKeys *
       group_keys__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GroupKeys *)
     protobuf_c_message_unpack (&group_keys__descriptor,
                                allocator, len, data);
}
void   group_keys__free_unpacked
                     (GroupKeys *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &group_keys__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pred_expression__init
                     (PredExpression         *message)
{
  static const PredExpression init_value = PRED_EXPRESSION__INIT;
  *message = init_value;
}
size_t pred_expression__get_packed_size
                     (const PredExpression *message)
{
  assert(message->base.descriptor == &pred_expression__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pred_expression__pack
                     (const PredExpression *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pred_expression__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pred_expression__pack_to_buffer
                     (const PredExpression *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pred_expression__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PredExpression *
       pred_expression__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PredExpression *)
     protobuf_c_message_unpack (&pred_expression__descriptor,
                                allocator, len, data);
}
void   pred_expression__free_unpacked
                     (PredExpression *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pred_expression__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   pred_operator__init
                     (PredOperator         *message)
{
  static const PredOperator init_value = PRED_OPERATOR__INIT;
  *message = init_value;
}
size_t pred_operator__get_packed_size
                     (const PredOperator *message)
{
  assert(message->base.descriptor == &pred_operator__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pred_operator__pack
                     (const PredOperator *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pred_operator__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pred_operator__pack_to_buffer
                     (const PredOperator *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pred_operator__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PredOperator *
       pred_operator__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PredOperator *)
     protobuf_c_message_unpack (&pred_operator__descriptor,
                                allocator, len, data);
}
void   pred_operator__free_unpacked
                     (PredOperator *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &pred_operator__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   quals__init
                     (Quals         *message)
{
  static const Quals init_value = QUALS__INIT;
  *message = init_value;
}
size_t quals__get_packed_size
                     (const Quals *message)
{
  assert(message->base.descriptor == &quals__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t quals__pack
                     (const Quals *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &quals__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t quals__pack_to_buffer
                     (const Quals *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &quals__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Quals *
       quals__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Quals *)
     protobuf_c_message_unpack (&quals__descriptor,
                                allocator, len, data);
}
void   quals__free_unpacked
                     (Quals *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &quals__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   proto_pred_equivlence__init
                     (ProtoPredEquivlence         *message)
{
  static const ProtoPredEquivlence init_value = PROTO_PRED_EQUIVLENCE__INIT;
  *message = init_value;
}
size_t proto_pred_equivlence__get_packed_size
                     (const ProtoPredEquivlence *message)
{
  assert(message->base.descriptor == &proto_pred_equivlence__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto_pred_equivlence__pack
                     (const ProtoPredEquivlence *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto_pred_equivlence__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto_pred_equivlence__pack_to_buffer
                     (const ProtoPredEquivlence *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto_pred_equivlence__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ProtoPredEquivlence *
       proto_pred_equivlence__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ProtoPredEquivlence *)
     protobuf_c_message_unpack (&proto_pred_equivlence__descriptor,
                                allocator, len, data);
}
void   proto_pred_equivlence__free_unpacked
                     (ProtoPredEquivlence *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto_pred_equivlence__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   range__init
                     (Range         *message)
{
  static const Range init_value = RANGE__INIT;
  *message = init_value;
}
size_t range__get_packed_size
                     (const Range *message)
{
  assert(message->base.descriptor == &range__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t range__pack
                     (const Range *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &range__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t range__pack_to_buffer
                     (const Range *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &range__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Range *
       range__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Range *)
     protobuf_c_message_unpack (&range__descriptor,
                                allocator, len, data);
}
void   range__free_unpacked
                     (Range *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &range__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   slow_plan_level_stat__init
                     (SlowPlanLevelStat         *message)
{
  static const SlowPlanLevelStat init_value = SLOW_PLAN_LEVEL_STAT__INIT;
  *message = init_value;
}
size_t slow_plan_level_stat__get_packed_size
                     (const SlowPlanLevelStat *message)
{
  assert(message->base.descriptor == &slow_plan_level_stat__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t slow_plan_level_stat__pack
                     (const SlowPlanLevelStat *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &slow_plan_level_stat__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t slow_plan_level_stat__pack_to_buffer
                     (const SlowPlanLevelStat *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &slow_plan_level_stat__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SlowPlanLevelStat *
       slow_plan_level_stat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SlowPlanLevelStat *)
     protobuf_c_message_unpack (&slow_plan_level_stat__descriptor,
                                allocator, len, data);
}
void   slow_plan_level_stat__free_unpacked
                     (SlowPlanLevelStat *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &slow_plan_level_stat__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   slow_plan_stat__init
                     (SlowPlanStat         *message)
{
  static const SlowPlanStat init_value = SLOW_PLAN_STAT__INIT;
  *message = init_value;
}
size_t slow_plan_stat__get_packed_size
                     (const SlowPlanStat *message)
{
  assert(message->base.descriptor == &slow_plan_stat__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t slow_plan_stat__pack
                     (const SlowPlanStat *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &slow_plan_stat__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t slow_plan_stat__pack_to_buffer
                     (const SlowPlanStat *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &slow_plan_stat__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SlowPlanStat *
       slow_plan_stat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SlowPlanStat *)
     protobuf_c_message_unpack (&slow_plan_stat__descriptor,
                                allocator, len, data);
}
void   slow_plan_stat__free_unpacked
                     (SlowPlanStat *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &slow_plan_stat__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor history_slow_plan_stat__field_descriptors[54] =
{
  {
    "custom_plan_provider",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, custom_plan_provider),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "estimate_plan_width",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, estimate_plan_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actual_nloops",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, actual_nloops),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actual_start_up",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, actual_start_up),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actual_total",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, actual_total),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actual_rows",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, actual_rows),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "childs",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(HistorySlowPlanStat, n_childs),
    offsetof(HistorySlowPlanStat, childs),
    &history_slow_plan_stat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node_type",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, node_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "strategy",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, strategy),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "partial_mode",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, partial_mode),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sub_plan_name",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, sub_plan_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "operation",
    14,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, operation),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object_name",
    15,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, object_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "schema",
    16,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, schema),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "object_tag",
    17,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, object_tag),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "alia_name",
    18,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, alia_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scan_dir",
    19,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, scan_dir),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "idx_name",
    20,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, idx_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "join_type",
    21,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, join_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inner_unique",
    22,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, inner_unique),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command",
    23,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, command),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output",
    24,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(HistorySlowPlanStat, n_output),
    offsetof(HistorySlowPlanStat, output),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "relationship",
    25,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, relationship),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "total_cost",
    26,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, total_cost),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sample_method",
    27,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, sample_method),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sampling_parameters",
    28,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, sampling_parameters),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "repeatable_seed",
    29,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, repeatable_seed),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sub_cost",
    30,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_DOUBLE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, sub_cost),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "json_plan",
    31,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, json_plan),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "canonical_json_plan",
    32,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, canonical_json_plan),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sub_node_type_set",
    33,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(HistorySlowPlanStat, n_sub_node_type_set),
    offsetof(HistorySlowPlanStat, sub_node_type_set),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qlabel",
    34,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, qlabel),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exprstr",
    35,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, exprstr),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key_name",
    36,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, key_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keysetname",
    37,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, keysetname),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_g_keys",
    38,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, is_g_keys),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "g_sets",
    39,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(HistorySlowPlanStat, n_g_sets),
    offsetof(HistorySlowPlanStat, g_sets),
    &group_keys__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group_sort_qlabel",
    40,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, group_sort_qlabel),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group_sort_keys",
    41,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(HistorySlowPlanStat, n_group_sort_keys),
    offsetof(HistorySlowPlanStat, group_sort_keys),
    &group_sort_key__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "node_tag",
    42,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, node_tag),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "expr_root",
    43,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, expr_root),
    &pred_expression__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cur_expr_tag",
    44,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, cur_expr_tag),
    &pred_type_tag__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "join_cond_expr_tree",
    45,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, join_cond_expr_tree),
    &pred_expression__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "join_filter_expr_tree",
    46,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, join_filter_expr_tree),
    &pred_expression__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "filter_tree",
    47,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, filter_tree),
    &pred_expression__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "one_time_filter_tree",
    48,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, one_time_filter_tree),
    &pred_expression__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tid_cond_expr_tree",
    49,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, tid_cond_expr_tree),
    &pred_expression__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recheck_cond_tree",
    50,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, recheck_cond_tree),
    &pred_expression__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index_cond_expr_tree",
    51,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, index_cond_expr_tree),
    &pred_expression__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "order_by_expr_tree",
    52,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, order_by_expr_tree),
    &pred_expression__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "child_idx",
    53,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, child_idx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subplan_idx",
    54,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, subplan_idx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subplans",
    55,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(HistorySlowPlanStat, n_subplans),
    offsetof(HistorySlowPlanStat, subplans),
    &history_slow_plan_stat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "canonical_node_json_plan",
    56,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(HistorySlowPlanStat, canonical_node_json_plan),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned history_slow_plan_stat__field_indices_by_name[] = {
  2,   /* field[2] = actual_nloops */
  5,   /* field[5] = actual_rows */
  3,   /* field[3] = actual_start_up */
  4,   /* field[4] = actual_total */
  15,   /* field[15] = alia_name */
  29,   /* field[29] = canonical_json_plan */
  53,   /* field[53] = canonical_node_json_plan */
  50,   /* field[50] = child_idx */
  6,   /* field[6] = childs */
  20,   /* field[20] = command */
  41,   /* field[41] = cur_expr_tag */
  0,   /* field[0] = custom_plan_provider */
  1,   /* field[1] = estimate_plan_width */
  40,   /* field[40] = expr_root */
  32,   /* field[32] = exprstr */
  44,   /* field[44] = filter_tree */
  36,   /* field[36] = g_sets */
  38,   /* field[38] = group_sort_keys */
  37,   /* field[37] = group_sort_qlabel */
  17,   /* field[17] = idx_name */
  48,   /* field[48] = index_cond_expr_tree */
  19,   /* field[19] = inner_unique */
  35,   /* field[35] = is_g_keys */
  42,   /* field[42] = join_cond_expr_tree */
  43,   /* field[43] = join_filter_expr_tree */
  18,   /* field[18] = join_type */
  28,   /* field[28] = json_plan */
  33,   /* field[33] = key_name */
  34,   /* field[34] = keysetname */
  39,   /* field[39] = node_tag */
  7,   /* field[7] = node_type */
  12,   /* field[12] = object_name */
  14,   /* field[14] = object_tag */
  45,   /* field[45] = one_time_filter_tree */
  11,   /* field[11] = operation */
  49,   /* field[49] = order_by_expr_tree */
  21,   /* field[21] = output */
  9,   /* field[9] = partial_mode */
  31,   /* field[31] = qlabel */
  47,   /* field[47] = recheck_cond_tree */
  22,   /* field[22] = relationship */
  26,   /* field[26] = repeatable_seed */
  24,   /* field[24] = sample_method */
  25,   /* field[25] = sampling_parameters */
  16,   /* field[16] = scan_dir */
  13,   /* field[13] = schema */
  8,   /* field[8] = strategy */
  27,   /* field[27] = sub_cost */
  30,   /* field[30] = sub_node_type_set */
  10,   /* field[10] = sub_plan_name */
  51,   /* field[51] = subplan_idx */
  52,   /* field[52] = subplans */
  46,   /* field[46] = tid_cond_expr_tree */
  23,   /* field[23] = total_cost */
};
static const ProtobufCIntRange history_slow_plan_stat__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 1 },
  { 0, 54 }
};
const ProtobufCMessageDescriptor history_slow_plan_stat__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "HistorySlowPlanStat",
  "HistorySlowPlanStat",
  "HistorySlowPlanStat",
  "",
  sizeof(HistorySlowPlanStat),
  54,
  history_slow_plan_stat__field_descriptors,
  history_slow_plan_stat__field_indices_by_name,
  2,  history_slow_plan_stat__number_ranges,
  (ProtobufCMessageInit) history_slow_plan_stat__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_sort_key__field_descriptors[6] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GroupSortKey, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sort_operators",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(GroupSortKey, sort_operators),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sort_collation",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GroupSortKey, sort_collation),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sort_direction",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GroupSortKey, sort_direction),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sort_null_pos",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GroupSortKey, sort_null_pos),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "presorted_key",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(GroupSortKey, presorted_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_sort_key__field_indices_by_name[] = {
  0,   /* field[0] = key */
  5,   /* field[5] = presorted_key */
  2,   /* field[2] = sort_collation */
  3,   /* field[3] = sort_direction */
  4,   /* field[4] = sort_null_pos */
  1,   /* field[1] = sort_operators */
};
static const ProtobufCIntRange group_sort_key__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor group_sort_key__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupSortKey",
  "GroupSortKey",
  "GroupSortKey",
  "",
  sizeof(GroupSortKey),
  6,
  group_sort_key__field_descriptors,
  group_sort_key__field_indices_by_name,
  1,  group_sort_key__number_ranges,
  (ProtobufCMessageInit) group_sort_key__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor group_keys__field_descriptors[2] =
{
  {
    "key_name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(GroupKeys, key_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keys",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(GroupKeys, n_keys),
    offsetof(GroupKeys, keys),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned group_keys__field_indices_by_name[] = {
  0,   /* field[0] = key_name */
  1,   /* field[1] = keys */
};
static const ProtobufCIntRange group_keys__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor group_keys__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "GroupKeys",
  "GroupKeys",
  "GroupKeys",
  "",
  sizeof(GroupKeys),
  2,
  group_keys__field_descriptors,
  group_keys__field_indices_by_name,
  1,  group_keys__number_ranges,
  (ProtobufCMessageInit) group_keys__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor pred_expression__field_descriptors[2] =
{
  {
    "op",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PredExpression, expr_case),
    offsetof(PredExpression, op),
    &pred_operator__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "qual",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PredExpression, expr_case),
    offsetof(PredExpression, qual),
    &quals__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pred_expression__field_indices_by_name[] = {
  0,   /* field[0] = op */
  1,   /* field[1] = qual */
};
static const ProtobufCIntRange pred_expression__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pred_expression__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PredExpression",
  "PredExpression",
  "PredExpression",
  "",
  sizeof(PredExpression),
  2,
  pred_expression__field_descriptors,
  pred_expression__field_indices_by_name,
  1,  pred_expression__number_ranges,
  (ProtobufCMessageInit) pred_expression__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue pred_operator__pred_operator_type__enum_values_by_number[3] =
{
  { "AND", "PRED_OPERATOR__PRED_OPERATOR_TYPE__AND", 0 },
  { "OR", "PRED_OPERATOR__PRED_OPERATOR_TYPE__OR", 1 },
  { "NOT", "PRED_OPERATOR__PRED_OPERATOR_TYPE__NOT", 2 },
};
static const ProtobufCIntRange pred_operator__pred_operator_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex pred_operator__pred_operator_type__enum_values_by_name[3] =
{
  { "AND", 0 },
  { "NOT", 2 },
  { "OR", 1 },
};
const ProtobufCEnumDescriptor pred_operator__pred_operator_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "PredOperator.PredOperatorType",
  "PredOperatorType",
  "PredOperator__PredOperatorType",
  "",
  3,
  pred_operator__pred_operator_type__enum_values_by_number,
  3,
  pred_operator__pred_operator_type__enum_values_by_name,
  1,
  pred_operator__pred_operator_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor pred_operator__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(PredOperator, type),
    &pred_operator__pred_operator_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "childs",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(PredOperator, n_childs),
    offsetof(PredOperator, childs),
    &pred_expression__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pred_operator__field_indices_by_name[] = {
  1,   /* field[1] = childs */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange pred_operator__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pred_operator__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PredOperator",
  "PredOperator",
  "PredOperator",
  "",
  sizeof(PredOperator),
  2,
  pred_operator__field_descriptors,
  pred_operator__field_indices_by_name,
  1,  pred_operator__number_ranges,
  (ProtobufCMessageInit) pred_operator__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor quals__field_descriptors[13] =
{
  {
    "left",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Quals, left),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Quals, right),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "op",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Quals, op),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "l_type",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Quals, l_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r_type",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Quals, r_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "format_type",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Quals, format_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use_or",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Quals, use_or),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hash_sub_plan",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Quals, hash_sub_plan),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sub_plan_name",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Quals, sub_plan_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hsps",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Quals, hsps),
    &history_slow_plan_stat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "left_val_type_id",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Quals, left_val_type_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "right_val_type_id",
    12,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Quals, right_val_type_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "root_hsps",
    13,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Quals, root_hsps),
    &history_slow_plan_stat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned quals__field_indices_by_name[] = {
  5,   /* field[5] = format_type */
  7,   /* field[7] = hash_sub_plan */
  9,   /* field[9] = hsps */
  3,   /* field[3] = l_type */
  0,   /* field[0] = left */
  10,   /* field[10] = left_val_type_id */
  2,   /* field[2] = op */
  4,   /* field[4] = r_type */
  1,   /* field[1] = right */
  11,   /* field[11] = right_val_type_id */
  12,   /* field[12] = root_hsps */
  8,   /* field[8] = sub_plan_name */
  6,   /* field[6] = use_or */
};
static const ProtobufCIntRange quals__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor quals__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Quals",
  "Quals",
  "Quals",
  "",
  sizeof(Quals),
  13,
  quals__field_descriptors,
  quals__field_indices_by_name,
  1,  quals__number_ranges,
  (ProtobufCMessageInit) quals__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor proto_pred_equivlence__field_descriptors[2] =
{
  {
    "sets",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ProtoPredEquivlence, n_sets),
    offsetof(ProtoPredEquivlence, sets),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ranges",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ProtoPredEquivlence, n_ranges),
    offsetof(ProtoPredEquivlence, ranges),
    &range__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto_pred_equivlence__field_indices_by_name[] = {
  1,   /* field[1] = ranges */
  0,   /* field[0] = sets */
};
static const ProtobufCIntRange proto_pred_equivlence__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor proto_pred_equivlence__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ProtoPredEquivlence",
  "ProtoPredEquivlence",
  "ProtoPredEquivlence",
  "",
  sizeof(ProtoPredEquivlence),
  2,
  proto_pred_equivlence__field_descriptors,
  proto_pred_equivlence__field_indices_by_name,
  1,  proto_pred_equivlence__number_ranges,
  (ProtobufCMessageInit) proto_pred_equivlence__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor range__field_descriptors[2] =
{
  {
    "str_lower_limit",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Range, str_lower_limit),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "str_upper_limit",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Range, str_upper_limit),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned range__field_indices_by_name[] = {
  0,   /* field[0] = str_lower_limit */
  1,   /* field[1] = str_upper_limit */
};
static const ProtobufCIntRange range__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor range__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Range",
  "Range",
  "Range",
  "",
  sizeof(Range),
  2,
  range__field_descriptors,
  range__field_indices_by_name,
  1,  range__number_ranges,
  (ProtobufCMessageInit) range__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor slow_plan_level_stat__field_descriptors[5] =
{
  {
    "pe_list",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SlowPlanLevelStat, n_pe_list),
    offsetof(SlowPlanLevelStat, pe_list),
    &proto_pred_equivlence__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output_col_set",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(SlowPlanLevelStat, n_output_col_set),
    offsetof(SlowPlanLevelStat, output_col_set),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group_by_set",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(SlowPlanLevelStat, n_group_by_set),
    offsetof(SlowPlanLevelStat, group_by_set),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sort_key_set",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(SlowPlanLevelStat, n_sort_key_set),
    offsetof(SlowPlanLevelStat, sort_key_set),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stop",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(SlowPlanLevelStat, stop),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slow_plan_level_stat__field_indices_by_name[] = {
  2,   /* field[2] = group_by_set */
  1,   /* field[1] = output_col_set */
  0,   /* field[0] = pe_list */
  3,   /* field[3] = sort_key_set */
  4,   /* field[4] = stop */
};
static const ProtobufCIntRange slow_plan_level_stat__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor slow_plan_level_stat__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SlowPlanLevelStat",
  "SlowPlanLevelStat",
  "SlowPlanLevelStat",
  "",
  sizeof(SlowPlanLevelStat),
  5,
  slow_plan_level_stat__field_descriptors,
  slow_plan_level_stat__field_indices_by_name,
  1,  slow_plan_level_stat__number_ranges,
  (ProtobufCMessageInit) slow_plan_level_stat__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor slow_plan_stat__field_descriptors[1] =
{
  {
    "stats",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SlowPlanStat, n_stats),
    offsetof(SlowPlanStat, stats),
    &slow_plan_level_stat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned slow_plan_stat__field_indices_by_name[] = {
  0,   /* field[0] = stats */
};
static const ProtobufCIntRange slow_plan_stat__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor slow_plan_stat__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SlowPlanStat",
  "SlowPlanStat",
  "SlowPlanStat",
  "",
  sizeof(SlowPlanStat),
  1,
  slow_plan_stat__field_descriptors,
  slow_plan_stat__field_indices_by_name,
  1,  slow_plan_stat__number_ranges,
  (ProtobufCMessageInit) slow_plan_stat__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue pred_type_tag__enum_values_by_number[9] =
{
  { "NONE", "PRED_TYPE_TAG__NONE", 0 },
  { "JOIN_COND", "PRED_TYPE_TAG__JOIN_COND", 1 },
  { "JOIN_FILTER", "PRED_TYPE_TAG__JOIN_FILTER", 2 },
  { "FILTER", "PRED_TYPE_TAG__FILTER", 3 },
  { "ONE_TIME_FILTER", "PRED_TYPE_TAG__ONE_TIME_FILTER", 4 },
  { "TID_COND", "PRED_TYPE_TAG__TID_COND", 5 },
  { "RECHECK_COND", "PRED_TYPE_TAG__RECHECK_COND", 6 },
  { "INDEX_COND", "PRED_TYPE_TAG__INDEX_COND", 7 },
  { "ORDER_BY", "PRED_TYPE_TAG__ORDER_BY", 8 },
};
static const ProtobufCIntRange pred_type_tag__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex pred_type_tag__enum_values_by_name[9] =
{
  { "FILTER", 3 },
  { "INDEX_COND", 7 },
  { "JOIN_COND", 1 },
  { "JOIN_FILTER", 2 },
  { "NONE", 0 },
  { "ONE_TIME_FILTER", 4 },
  { "ORDER_BY", 8 },
  { "RECHECK_COND", 6 },
  { "TID_COND", 5 },
};
const ProtobufCEnumDescriptor pred_type_tag__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "PredTypeTag",
  "PredTypeTag",
  "PredTypeTag",
  "",
  9,
  pred_type_tag__enum_values_by_number,
  9,
  pred_type_tag__enum_values_by_name,
  1,
  pred_type_tag__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue val_type__enum_values_by_number[6] =
{
  { "UNKNOWN", "VAL_TYPE__UNKNOWN", 0 },
  { "INT", "VAL_TYPE__INT", 1 },
  { "DOUBLE", "VAL_TYPE__DOUBLE", 2 },
  { "STRING", "VAL_TYPE__STRING", 3 },
  { "BOOL", "VAL_TYPE__BOOL", 4 },
  { "NULL", "VAL_TYPE__NULL", 5 },
};
static const ProtobufCIntRange val_type__value_ranges[] = {
{0, 0},{0, 6}
};
static const ProtobufCEnumValueIndex val_type__enum_values_by_name[6] =
{
  { "BOOL", 4 },
  { "DOUBLE", 2 },
  { "INT", 1 },
  { "NULL", 5 },
  { "STRING", 3 },
  { "UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor val_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "ValType",
  "ValType",
  "ValType",
  "",
  6,
  val_type__enum_values_by_number,
  6,
  val_type__enum_values_by_name,
  1,
  val_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
