/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: format.proto */

#ifndef PROTOBUF_C_format_2eproto__INCLUDED
#define PROTOBUF_C_format_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _HistorySlowPlanStat HistorySlowPlanStat;


/* --- enums --- */


/* --- messages --- */

struct  _HistorySlowPlanStat
{
  ProtobufCMessage base;
  double estimate_start_up_cost_;
  double estimate_total_cost_;
  double estimate_plan_rows_;
  double estimate_plan_width_;
  double actual_nloops_;
  double actual_start_up_;
  double actual_total_;
  double actual_rows_;
  size_t n_childs;
  HistorySlowPlanStat **childs;
  char *node_type_;
  char *strategy_;
  /*
   *for aggregate
   */
  char *partial_mode_;
  /*
   *for subplan
   */
  char *sub_plan_name_;
  /*
   *for insert/update/delete
   */
  char *operation_;
  /*
   *for scan
   */
  char *object_name_;
  char *schema_;
  char *object_tag_;
  char *alia_name_;
  /*
   *addtional info for indexscan/indexonlyscan
   */
  char *scan_dir_;
  char *idx_name_;
  /*
   *for join
   */
  char *join_type_;
  protobuf_c_boolean inner_unique_;
  /*
   *for setOp
   */
  char *command_;
  /*
   *output cols
   */
  size_t n_output_;
  char **output_;
  char *relationship_;
  double total_cost_;
  char *sample_method_;
  char *sampling_parameters_;
  char *repeatable_seed_;
  /*
   *total cost of current subquery
   */
  double sub_cost_;
  /*
   *json of current subquery
   */
  char *json_plan_;
  /*
   *all node type of current subquery
   */
  size_t n_sub_node_type_set;
  char **sub_node_type_set;
  /*
   *all prdicates of current subquery
   */
  size_t n_sub_pref_type_set;
  char **sub_pref_type_set;
};
#define HISTORY_SLOW_PLAN_STAT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&history_slow_plan_stat__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0,NULL, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0,NULL, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, 0,NULL, 0,NULL }


/* HistorySlowPlanStat methods */
void   history_slow_plan_stat__init
                     (HistorySlowPlanStat         *message);
size_t history_slow_plan_stat__get_packed_size
                     (const HistorySlowPlanStat   *message);
size_t history_slow_plan_stat__pack
                     (const HistorySlowPlanStat   *message,
                      uint8_t             *out);
size_t history_slow_plan_stat__pack_to_buffer
                     (const HistorySlowPlanStat   *message,
                      ProtobufCBuffer     *buffer);
HistorySlowPlanStat *
       history_slow_plan_stat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   history_slow_plan_stat__free_unpacked
                     (HistorySlowPlanStat *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*HistorySlowPlanStat_Closure)
                 (const HistorySlowPlanStat *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor history_slow_plan_stat__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_format_2eproto__INCLUDED */
